channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.14.3
  - cloudpickle==1.6.0
  - jinja2==3.1.4
  - numpy==1.26.4
  - llama-cpp-python==0.3.6
  - pandas==2.2.3
name: mlflow-env